......................................................................
:                                                                    :
: This has been a full user-base email from the SensiSummink talker. :
: If you have never heard of this talker, then please reply to this  :
: message for the matter to be resolved.                             :
:                                                                    :
: Thankyou on behalf of the SensiSummink admin.                      :
:....................................................................:
